package protocgen

import (
	"fmt"
	"path"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

const weaverImportPath = protogen.GoImportPath("github.com/project-kgo/weaver")

var (
	contextImportPath = protogen.GoImportPath("context")
	httpImportPath    = protogen.GoImportPath("net/http")
	connectImportPath = protogen.GoImportPath("connectrpc.com/connect")
)

// Generate 为所有 unary protobuf service 生成 Weaver 胶水代码。
func Generate(plugin *protogen.Plugin) error {
	for _, file := range plugin.Files {
		if !file.Generate || len(file.Services) == 0 {
			continue
		}
		for _, service := range file.Services {
			for _, method := range service.Methods {
				if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
					return fmt.Errorf("weaver: service %s 的方法 %s 使用了 streaming；v0.1 仅支持 unary RPC", service.Desc.FullName(), method.Desc.Name())
				}
			}
		}
		generateFile(plugin, file)
	}
	return nil
}

func generateFile(plugin *protogen.Plugin, file *protogen.File) {
	directory := path.Dir(file.GeneratedFilenamePrefix)
	base := path.Base(file.GeneratedFilenamePrefix)
	packageName := string(file.GoPackageName) + "weaver"
	filename := path.Join(directory, packageName, base+".weaver.go")
	componentImportPath := protogen.GoImportPath(path.Join(string(file.GoImportPath), packageName))
	connectPackagePath := protogen.GoImportPath(path.Join(string(file.GoImportPath), string(file.GoPackageName)+"connect"))

	generated := plugin.NewGeneratedFile(filename, componentImportPath)
	generated.P("// Code generated by protoc-gen-weaver-go. DO NOT EDIT.")
	generated.P()
	generated.P("package ", packageName)
	generated.P()

	for _, service := range file.Services {
		generateService(generated, service, connectPackagePath)
	}
}

func generateService(generated *protogen.GeneratedFile, service *protogen.Service, connectPackagePath protogen.GoImportPath) {
	serviceName := service.GoName
	componentName := serviceName + "Component"
	localClientName := lowerFirst(serviceName) + "LocalClient"
	clientInterface := protogen.GoIdent{GoName: serviceName + "Client", GoImportPath: connectPackagePath}
	newClient := protogen.GoIdent{GoName: "New" + serviceName + "Client", GoImportPath: connectPackagePath}
	newHandler := protogen.GoIdent{GoName: "New" + serviceName + "Handler", GoImportPath: connectPackagePath}

	generated.P("const ", serviceName, "Name = ", fmt.Sprintf("%q", service.Desc.FullName()))
	generated.P()
	generated.P("type ", componentName, " interface {")
	generated.P(generated.QualifiedGoIdent(clientInterface))
	generated.P("}")
	generated.P()
	generated.P("var ", serviceName, " = ", generated.QualifiedGoIdent(weaverImportPath.Ident("Service")), "[", componentName, "]{")
	generated.P("Name: ", serviceName, "Name,")
	generated.P("NewLocal: func(implementation ", componentName, ") ", componentName, " {")
	generated.P("return &", localClientName, "{implementation: implementation}")
	generated.P("},")
	generated.P("NewRemote: func(client ", generated.QualifiedGoIdent(connectImportPath.Ident("HTTPClient")), ", baseURL string, options ...", generated.QualifiedGoIdent(connectImportPath.Ident("ClientOption")), ") ", componentName, " {")
	generated.P("return ", generated.QualifiedGoIdent(newClient), "(client, baseURL, options...)")
	generated.P("},")
	generated.P("NewHandler: func(implementation ", componentName, ", options ...", generated.QualifiedGoIdent(connectImportPath.Ident("HandlerOption")), ") (string, ", generated.QualifiedGoIdent(httpImportPath.Ident("Handler")), ") {")
	generated.P("return ", generated.QualifiedGoIdent(newHandler), "(implementation, options...)")
	generated.P("},")
	generated.P("}")
	generated.P()
	generated.P("type ", localClientName, " struct {")
	generated.P("implementation ", componentName)
	generated.P("}")
	generated.P()

	for _, method := range service.Methods {
		generated.P("func (client *", localClientName, ") ", method.GoName, "(ctx ", generated.QualifiedGoIdent(contextImportPath.Ident("Context")), ", request *", generated.QualifiedGoIdent(method.Input.GoIdent), ") (*", generated.QualifiedGoIdent(method.Output.GoIdent), ", error) {")
		generated.P("response, err := client.implementation.", method.GoName, "(ctx, request)")
		generated.P("if err != nil {")
		generated.P("return nil, ", generated.QualifiedGoIdent(weaverImportPath.Ident("NormalizeError")), "(err)")
		generated.P("}")
		generated.P("return response, nil")
		generated.P("}")
		generated.P()
	}
}

func lowerFirst(value string) string {
	if value == "" {
		return value
	}
	return strings.ToLower(value[:1]) + value[1:]
}
