// Code generated by weaver generate. DO NOT EDIT.

package app

import (
	weaver "github.com/project-kgo/weaver"
	examplev1weaver "github.com/project-kgo/weaver/examples/echo/gen/example/v1/examplev1weaver"
	reflect "reflect"
)

var _ [weaver.CodegenVersion]struct{} = [3]struct{}{}

func init() {
	weaver.MustRegister(weaver.Registration{
		Service: examplev1weaver.EchoService.Descriptor(),
		New:     func() any { return new(echoService) },
		Inject: func(target any, injector weaver.Injector) error {
			component := target.(*echoService)
			ref0, err := weaver.ResolveComponent[examplev1weaver.UpperServiceComponent](injector, examplev1weaver.UpperService.Name)
			if err != nil {
				return err
			}
			weaver.SetRef(&component.Upper, ref0)
			return nil
		},
		Dependencies: []string{
			examplev1weaver.UpperService.Name,
		},
	})
	weaver.MustRegister(weaver.Registration{
		Service:    examplev1weaver.UpperService.Descriptor(),
		ConfigType: reflect.TypeFor[Settings](),
		New:        func() any { return new(upperService) },
		Inject: func(target any, injector weaver.Injector) error {
			component := target.(*upperService)
			config, err := weaver.ResolveConfig[Settings](injector)
			if err != nil {
				return err
			}
			weaver.SetConfig(&component.WithConfig, config)
			return nil
		},
	})
}

var _ examplev1weaver.EchoServiceComponent = (*echoService)(nil)
var _ examplev1weaver.UpperServiceComponent = (*upperService)(nil)
